// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zwmuujuazyrymewljquu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bXV1anVhenlyeW1ld2xqcXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTA0NzgsImV4cCI6MjA4ODQ4NjQ3OH0.A5rkfs4XX2XqoiZrXc0FUjX-zFtLB1Ps4evtuVUIc3w";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);